package watcher

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/fsnotify/fsnotify"
	"github.com/okyashgajjar/costaffective-mcp/internal/cache"
	"github.com/okyashgajjar/costaffective-mcp/internal/session"
)

type Watchdog struct {
	repoSession *session.RepoSession
	watcher     *fsnotify.Watcher
	ctx         context.Context
	cancel      context.CancelFunc
	mu          sync.Mutex
	timer       *time.Timer
}

func NewWatchdog(rs *session.RepoSession) (*Watchdog, error) {
	w, err := fsnotify.NewWatcher()
	if err != nil {
		return nil, fmt.Errorf("failed to create watcher: %w", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	return &Watchdog{
		repoSession: rs,
		watcher:     w,
		ctx:         ctx,
		cancel:      cancel,
	}, nil
}

func (wd *Watchdog) Start() error {
	root := wd.repoSession.Repo.Root

	// Add all subdirectories to watcher recursively, skipping ignored dirs
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			base := filepath.Base(path)
			if base == ".git" || base == "node_modules" || base == "vendor" || base == ".codegraph" {
				return filepath.SkipDir
			}
			_ = wd.watcher.Add(path)
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("failed to walk directories for watcher: %w", err)
	}

	go wd.watchLoop()
	log.Printf("Watchdog started on %s", root)
	return nil
}

func (wd *Watchdog) watchLoop() {
	defer wd.watcher.Close()

	for {
		select {
		case <-wd.ctx.Done():
			return
		case event, ok := <-wd.watcher.Events:
			if !ok {
				return
			}
			
			// Ignore temporary or swap files usually generated by editors
			if strings.HasSuffix(event.Name, "~") || strings.HasSuffix(event.Name, ".swp") || strings.HasPrefix(filepath.Base(event.Name), ".gopls") {
				continue
			}

			// Add new directories to watcher
			if event.Has(fsnotify.Create) {
				if info, err := os.Stat(event.Name); err == nil && info.IsDir() {
					_ = wd.watcher.Add(event.Name)
				}
			}

			if event.Has(fsnotify.Write) || event.Has(fsnotify.Create) || event.Has(fsnotify.Remove) || event.Has(fsnotify.Rename) {
				wd.triggerReindex()
			}
		case err, ok := <-wd.watcher.Errors:
			if !ok {
				return
			}
			log.Printf("Watchdog error: %v", err)
		}
	}
}

func (wd *Watchdog) triggerReindex() {
	wd.mu.Lock()
	defer wd.mu.Unlock()

	if wd.timer != nil {
		wd.timer.Stop()
	}

	wd.timer = time.AfterFunc(1000*time.Millisecond, func() {
		log.Println("Watchdog: changes detected, starting incremental reindex...")
		ctx := context.Background()
		result, err := wd.repoSession.Indexer.Index(ctx)
		if err != nil {
			log.Printf("Watchdog: failed to reindex: %v", err)
			return
		}
		if result.Changed > 0 || result.Deleted > 0 {
			log.Printf("Watchdog: reindex complete (Changed: %d, Skipped: %d, Deleted: %d, Total: %d)", result.Changed, result.Skipped, result.Deleted, result.Total)
			if wd.repoSession.Cache != nil {
				// Invalidate the cache for this repository
				repoHash := cache.RepoHash(wd.repoSession.Repo.Root)
				wd.repoSession.Cache.Invalidate(repoHash)
				log.Println("Watchdog: cache invalidated")
			}
		}
	})
}

func (wd *Watchdog) Stop() {
	wd.cancel()
	if wd.watcher != nil {
		_ = wd.watcher.Close()
	}
}
